version: '3.8'
services:
    node-red:
        depends_on:
            - influx
        container_name: nodered
        image: nodered/node-red:latest
        environment:
            - TZ=America/Mexico_City
        ports:
            - 1880:1880
        restart: always
        volumes:
            - ./data:/data

    influx:
        container_name: influxdb
        image: influxdb:latest
        environment:
            - INFLUXDB_HTTP_AUTH_ENABLED=TRUE
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
            - INFLUXDB_USER=user
            - INFLUXDB_USER_PASSWORD=user
            - INFLUXDB_READ_USER=user
            - INFLUXDB_READ_USER_PASSWORD=userR
            - INFLUXDB_DB=influxdb
        volumes:
            - influx_data:/var/lib/influxdb

    grafana:
        depends_on:
            - influx
        container_name: grafana
        image: grafana/grafana:latest
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GRAFANA_INFLUX_DB=influxdb
            - GRAFANA_INFLUX_USER=admin
            - GRAFANA_INFLUX_PASSWORD=admin
        volumes:
            - grafana_data:/var/lib/grafana
        ports:
            - 3000:3000

volumes:
    grafana_data:
    influx_data: